class UserProfileModel {
  String fullName,
      profileImage,
      coverPhoto,
      phone,
      mobile,
      postalCode,
      city,
      otherEmail,
      twitter,
      whatsapp,
      address,
      ageOfBirth,
      weight,
      height,
      bike,
      instagram,
      country,
      heightUnit,
      weightUnit,
      facebook,
      credits,
      profileProgress;

  UserProfileModel({
    required this.fullName,
    required this.profileImage,
    required this.coverPhoto,
    required this.phone,
    required this.mobile,
    required this.postalCode,
    required this.city,
    required this.otherEmail,
    required this.twitter,
    required this.whatsapp,
    required this.address,
    required this.ageOfBirth,
    required this.weight,
    required this.height,
    required this.bike,
    required this.instagram,
    required this.country,
    required this.heightUnit,
    required this.weightUnit,
    required this.facebook,
    required this.credits,
    required this.profileProgress,
  });

  factory UserProfileModel.fromJson(Map<String, dynamic> json) {
    return UserProfileModel(
      fullName: json['full_name'].toString(),
      profileImage: json['profile_image'].toString(),
      coverPhoto: json['cover_photo'].toString(),
      phone: json['phone'].toString(),
      mobile: json['mobile'].toString(),
      postalCode: json['postal_code'].toString(),
      city: json['city'].toString(),
      otherEmail: json['other_email'].toString(),
      twitter: json['twitter'].toString(),
      whatsapp: json['whatsapp'].toString(),
      address: json['address'].toString(),
      ageOfBirth: json['dob'].toString(),
      weight: json['weight'].toString(),
      height: json['height'].toString(),
      bike: json['bike'].toString(),
      instagram: json['instagram'].toString(),
      country: json['country'].toString(),
      heightUnit: json['height_unit'].toString(),
      weightUnit: json['weight_unit'].toString(),
      facebook: json['facebook'].toString(),
      credits: json['credits'].toString(),
      profileProgress: json['profile_progress'].toString(),
    );
  }
}
